
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '2F32B8413F5F9B727789AC714F752AEF'
    
_lr_action_items = {'UNION':([1,2,4,5,7,9,10,11,],[-6,-5,6,6,-4,-1,-2,-3,]),'LPAREN':([0,3,6,8,],[3,3,3,3,]),'CONCATE':([1,2,4,5,7,9,10,11,],[-6,-5,8,8,-4,-1,8,-3,]),'RPAREN':([1,2,5,7,9,10,11,],[-6,-5,9,-4,-1,-2,-3,]),'EPSILON':([0,3,6,8,],[2,2,2,2,]),'$end':([1,2,4,7,9,10,11,],[-6,-5,0,-4,-1,-2,-3,]),'CLOSURE':([1,2,4,5,7,9,10,11,],[-6,-5,7,7,-4,-1,7,7,]),'SIM':([0,3,6,8,],[1,1,1,1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,3,6,8,],[4,5,10,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_group','regular.py',65),
  ('expr -> expr UNION expr','expr',3,'p_expr_union','regular.py',69),
  ('expr -> expr CONCATE expr','expr',3,'p_expr_concate','regular.py',97),
  ('expr -> expr CLOSURE','expr',2,'p_expr_closure','regular.py',120),
  ('expr -> EPSILON','expr',1,'p_expr_eps','regular.py',138),
  ('expr -> SIM','expr',1,'p_expr_sym','regular.py',142),
]
